name: ${project.name}
main: ${project.group}
version: ${project.version}
api-version: 1.16
depend:
  - FITask
  - FITaskGui
  - PlaceholderAPI
  - FICore
authors: [GSQ_FI]
commands:
  fitpokecr:
    description: main cmd